# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wireshark/compl_compu_trabajo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wireshark/compl_compu_trabajo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wireshark/compl_compu_trabajo/CMakeFiles /home/wireshark/compl_compu_trabajo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wireshark/compl_compu_trabajo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 3dm_to_partition

# Build rule for target.
3dm_to_partition: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 3dm_to_partition
.PHONY : 3dm_to_partition

# fast build rule for target.
3dm_to_partition/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/build
.PHONY : 3dm_to_partition/fast

src/core/partition_element.o: src/core/partition_element.cc.o
.PHONY : src/core/partition_element.o

# target to build an object file
src/core/partition_element.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/core/partition_element.cc.o
.PHONY : src/core/partition_element.cc.o

src/core/partition_element.i: src/core/partition_element.cc.i
.PHONY : src/core/partition_element.i

# target to preprocess a source file
src/core/partition_element.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/core/partition_element.cc.i
.PHONY : src/core/partition_element.cc.i

src/core/partition_element.s: src/core/partition_element.cc.s
.PHONY : src/core/partition_element.s

# target to generate assembly for a file
src/core/partition_element.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/core/partition_element.cc.s
.PHONY : src/core/partition_element.cc.s

src/core/partition_instance.o: src/core/partition_instance.cc.o
.PHONY : src/core/partition_instance.o

# target to build an object file
src/core/partition_instance.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/core/partition_instance.cc.o
.PHONY : src/core/partition_instance.cc.o

src/core/partition_instance.i: src/core/partition_instance.cc.i
.PHONY : src/core/partition_instance.i

# target to preprocess a source file
src/core/partition_instance.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/core/partition_instance.cc.i
.PHONY : src/core/partition_instance.cc.i

src/core/partition_instance.s: src/core/partition_instance.cc.s
.PHONY : src/core/partition_instance.s

# target to generate assembly for a file
src/core/partition_instance.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/core/partition_instance.cc.s
.PHONY : src/core/partition_instance.cc.s

src/core/three_d_m_instance.o: src/core/three_d_m_instance.cc.o
.PHONY : src/core/three_d_m_instance.o

# target to build an object file
src/core/three_d_m_instance.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/core/three_d_m_instance.cc.o
.PHONY : src/core/three_d_m_instance.cc.o

src/core/three_d_m_instance.i: src/core/three_d_m_instance.cc.i
.PHONY : src/core/three_d_m_instance.i

# target to preprocess a source file
src/core/three_d_m_instance.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/core/three_d_m_instance.cc.i
.PHONY : src/core/three_d_m_instance.cc.i

src/core/three_d_m_instance.s: src/core/three_d_m_instance.cc.s
.PHONY : src/core/three_d_m_instance.s

# target to generate assembly for a file
src/core/three_d_m_instance.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/core/three_d_m_instance.cc.s
.PHONY : src/core/three_d_m_instance.cc.s

src/core/triple.o: src/core/triple.cc.o
.PHONY : src/core/triple.o

# target to build an object file
src/core/triple.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/core/triple.cc.o
.PHONY : src/core/triple.cc.o

src/core/triple.i: src/core/triple.cc.i
.PHONY : src/core/triple.i

# target to preprocess a source file
src/core/triple.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/core/triple.cc.i
.PHONY : src/core/triple.cc.i

src/core/triple.s: src/core/triple.cc.s
.PHONY : src/core/triple.s

# target to generate assembly for a file
src/core/triple.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/core/triple.cc.s
.PHONY : src/core/triple.cc.s

src/interactive_shell_main.o: src/interactive_shell_main.cc.o
.PHONY : src/interactive_shell_main.o

# target to build an object file
src/interactive_shell_main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/interactive_shell_main.cc.o
.PHONY : src/interactive_shell_main.cc.o

src/interactive_shell_main.i: src/interactive_shell_main.cc.i
.PHONY : src/interactive_shell_main.i

# target to preprocess a source file
src/interactive_shell_main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/interactive_shell_main.cc.i
.PHONY : src/interactive_shell_main.cc.i

src/interactive_shell_main.s: src/interactive_shell_main.cc.s
.PHONY : src/interactive_shell_main.s

# target to generate assembly for a file
src/interactive_shell_main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/interactive_shell_main.cc.s
.PHONY : src/interactive_shell_main.cc.s

src/io/partition_reader.o: src/io/partition_reader.cc.o
.PHONY : src/io/partition_reader.o

# target to build an object file
src/io/partition_reader.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/io/partition_reader.cc.o
.PHONY : src/io/partition_reader.cc.o

src/io/partition_reader.i: src/io/partition_reader.cc.i
.PHONY : src/io/partition_reader.i

# target to preprocess a source file
src/io/partition_reader.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/io/partition_reader.cc.i
.PHONY : src/io/partition_reader.cc.i

src/io/partition_reader.s: src/io/partition_reader.cc.s
.PHONY : src/io/partition_reader.s

# target to generate assembly for a file
src/io/partition_reader.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/io/partition_reader.cc.s
.PHONY : src/io/partition_reader.cc.s

src/io/partition_writer.o: src/io/partition_writer.cc.o
.PHONY : src/io/partition_writer.o

# target to build an object file
src/io/partition_writer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/io/partition_writer.cc.o
.PHONY : src/io/partition_writer.cc.o

src/io/partition_writer.i: src/io/partition_writer.cc.i
.PHONY : src/io/partition_writer.i

# target to preprocess a source file
src/io/partition_writer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/io/partition_writer.cc.i
.PHONY : src/io/partition_writer.cc.i

src/io/partition_writer.s: src/io/partition_writer.cc.s
.PHONY : src/io/partition_writer.s

# target to generate assembly for a file
src/io/partition_writer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/io/partition_writer.cc.s
.PHONY : src/io/partition_writer.cc.s

src/io/three_d_m_reader.o: src/io/three_d_m_reader.cc.o
.PHONY : src/io/three_d_m_reader.o

# target to build an object file
src/io/three_d_m_reader.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/io/three_d_m_reader.cc.o
.PHONY : src/io/three_d_m_reader.cc.o

src/io/three_d_m_reader.i: src/io/three_d_m_reader.cc.i
.PHONY : src/io/three_d_m_reader.i

# target to preprocess a source file
src/io/three_d_m_reader.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/io/three_d_m_reader.cc.i
.PHONY : src/io/three_d_m_reader.cc.i

src/io/three_d_m_reader.s: src/io/three_d_m_reader.cc.s
.PHONY : src/io/three_d_m_reader.s

# target to generate assembly for a file
src/io/three_d_m_reader.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/io/three_d_m_reader.cc.s
.PHONY : src/io/three_d_m_reader.cc.s

src/io/three_d_m_writer.o: src/io/three_d_m_writer.cc.o
.PHONY : src/io/three_d_m_writer.o

# target to build an object file
src/io/three_d_m_writer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/io/three_d_m_writer.cc.o
.PHONY : src/io/three_d_m_writer.cc.o

src/io/three_d_m_writer.i: src/io/three_d_m_writer.cc.i
.PHONY : src/io/three_d_m_writer.i

# target to preprocess a source file
src/io/three_d_m_writer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/io/three_d_m_writer.cc.i
.PHONY : src/io/three_d_m_writer.cc.i

src/io/three_d_m_writer.s: src/io/three_d_m_writer.cc.s
.PHONY : src/io/three_d_m_writer.s

# target to generate assembly for a file
src/io/three_d_m_writer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/io/three_d_m_writer.cc.s
.PHONY : src/io/three_d_m_writer.cc.s

src/reduction/three_d_m_to_partition_reducer.o: src/reduction/three_d_m_to_partition_reducer.cc.o
.PHONY : src/reduction/three_d_m_to_partition_reducer.o

# target to build an object file
src/reduction/three_d_m_to_partition_reducer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/reduction/three_d_m_to_partition_reducer.cc.o
.PHONY : src/reduction/three_d_m_to_partition_reducer.cc.o

src/reduction/three_d_m_to_partition_reducer.i: src/reduction/three_d_m_to_partition_reducer.cc.i
.PHONY : src/reduction/three_d_m_to_partition_reducer.i

# target to preprocess a source file
src/reduction/three_d_m_to_partition_reducer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/reduction/three_d_m_to_partition_reducer.cc.i
.PHONY : src/reduction/three_d_m_to_partition_reducer.cc.i

src/reduction/three_d_m_to_partition_reducer.s: src/reduction/three_d_m_to_partition_reducer.cc.s
.PHONY : src/reduction/three_d_m_to_partition_reducer.s

# target to generate assembly for a file
src/reduction/three_d_m_to_partition_reducer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3dm_to_partition.dir/build.make CMakeFiles/3dm_to_partition.dir/src/reduction/three_d_m_to_partition_reducer.cc.s
.PHONY : src/reduction/three_d_m_to_partition_reducer.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... 3dm_to_partition"
	@echo "... src/core/partition_element.o"
	@echo "... src/core/partition_element.i"
	@echo "... src/core/partition_element.s"
	@echo "... src/core/partition_instance.o"
	@echo "... src/core/partition_instance.i"
	@echo "... src/core/partition_instance.s"
	@echo "... src/core/three_d_m_instance.o"
	@echo "... src/core/three_d_m_instance.i"
	@echo "... src/core/three_d_m_instance.s"
	@echo "... src/core/triple.o"
	@echo "... src/core/triple.i"
	@echo "... src/core/triple.s"
	@echo "... src/interactive_shell_main.o"
	@echo "... src/interactive_shell_main.i"
	@echo "... src/interactive_shell_main.s"
	@echo "... src/io/partition_reader.o"
	@echo "... src/io/partition_reader.i"
	@echo "... src/io/partition_reader.s"
	@echo "... src/io/partition_writer.o"
	@echo "... src/io/partition_writer.i"
	@echo "... src/io/partition_writer.s"
	@echo "... src/io/three_d_m_reader.o"
	@echo "... src/io/three_d_m_reader.i"
	@echo "... src/io/three_d_m_reader.s"
	@echo "... src/io/three_d_m_writer.o"
	@echo "... src/io/three_d_m_writer.i"
	@echo "... src/io/three_d_m_writer.s"
	@echo "... src/reduction/three_d_m_to_partition_reducer.o"
	@echo "... src/reduction/three_d_m_to_partition_reducer.i"
	@echo "... src/reduction/three_d_m_to_partition_reducer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

